function shortCityLabel(name: string): string {
  const trimmed = name.trim();
  const beforeParen = trimmed.split('(')[0]?.trim();
  return beforeParen || trimmed;
}

/** Quartiers par ville (clé = libellé court de la zone, ex. Yaoundé, Douala). */
export const DELIVERY_NEIGHBORHOODS: Record<string, string[]> = {
  Yaoundé: [
    'Abom',
    'Afanoya',
    'Ahala 1',
    'Ahala 2',
    'Anguissa',
    'Awae',
    'Bastos',
    'Biyem-Assi',
    'Biteng',
    'Briqueterie',
    'Centre-ville',
    'Cité Verte',
    'Dakar',
    'Efoulan',
    'Ekie',
    'Ekoudou',
    'Ekoumdoum',
    'Ekounou',
    'Elig-Edzoa',
    'Elig-Effa',
    'Elig-Essono',
    'Eleveur',
    'Emana',
    'Emombo',
    'Essos',
    'Etam-Bafia',
    'Etoa',
    'Etoa-Meki',
    'Etetak',
    'Etoudi',
    'Etoug-Ebe',
    'Febe',
    'Grand Messa',
    'Kondengui',
    'Madagascar',
    'Manguier',
    'Mballa',
    'Mbankolo',
    'Mebandan',
    'Mekoumbou',
    'Melen',
    'Mendong',
    'Messa',
    'Messa Carrière',
    'Messame-Ndongo',
    'Messassi',
    'Mfandena',
    'Mfoundi',
    'Mimboman',
    'Minkoameyos',
    'Mokolo',
    'Mvan',
    'Mvog-Ada',
    'Mvog-Betsi',
    'Mvog-Mbi',
    'Mvolyé',
    'Ndamvout',
    'Ngoa-Ekélé',
    'Ngousso',
    'Ngousso-Ntem',
    'Ngoulmekong',
    'Nkol-Ebogo',
    'Nkol-Ndongo',
    'Nkolfon',
    'Nkolbikok',
    'Nkolbisson',
    'Nkolmesseng',
    'Nkolondom',
    'Nkolso',
    'Nkom-Kana',
    'Nkomo',
    'Nkoleton',
    'Nlongkak',
    'Nsam',
    'Nsimeyong',
    'Ntouessong',
    'Ntoungou',
    'Ntui-Essong',
    'Nyom',
    'Obobogo',
    'Obili',
    'Odza',
    'Okolo',
    'Olembé',
    'Olezoa',
    'Oliga',
    'Omnisports',
    'Oyomabang',
    'Quartier Fouda',
    'Simbock',
    'Tongolo',
    'Tsinga',
    'Autre quartier',
  ],
  Douala: [
    'Aéroport',
    'Akwa',
    'Babylone',
    'Bali',
    'Bangue',
    'Bassa',
    'Bépanda',
    'Besseke',
    'Bessengue',
    'Bilongue',
    'Bobongo',
    'Boko',
    'Bonabéri',
    'Bonadibong',
    'Bonadoumbé',
    'Bonalembe',
    'Bonamikano',
    'Bonamoussadi',
    'Bonanjo',
    'Bonapriso',
    'Bonassama',
    'Bonateki',
    'Bonendale',
    'C.C.C.',
    'Cité SIC',
    'Cité des Palmiers',
    'Congo',
    'Deïdo',
    'Denver',
    'Djébalè',
    'Grand-Moulin',
    'Japoma',
    'Kassalafam',
    'Kotto',
    'Koumassi',
    'Logbaba',
    'Logbessou',
    'Logpom',
    'Madagascar',
    'Makepe',
    'Makepe Maturité',
    'Makepe Missokè',
    'Mambanda',
    'Mboppi',
    'Ndobo',
    'Ndogbati',
    'Ndogbong',
    'Ndoghem',
    'Ndogpassi',
    'Ndogsimbi',
    'Ndokoti',
    'New Bell',
    'New Deïdo',
    'Ngangue',
    'Ngodi-Bakoko',
    'Ngoma',
    'Nyalla',
    'Nylon',
    'PK7',
    'PK9',
    'PK10',
    'PK14',
    'Plateau Joss',
    'Santa Barbara',
    'So-Boum',
    'Sodiko',
    'Song-Mahop',
    'Tergal',
    'Yassa',
    'Youpwé',
    'Autre quartier',
  ],
  Bafoussam: [
    'Bamendzi',
    'Bamougoum',
    'Banengo',
    'Bapi',
    'Centre-ville',
    'Djeleng',
    'Djemoun',
    'Famla',
    'Kamkop',
    'Koptchou',
    'Lafe',
    'Ndiangdam',
    'Ngoueng',
    'Nkwabang',
    'Quartier Administratif',
    'Quartier Évêché',
    'Quartier Haoussa',
    'Tamdja',
    'Toukouop',
    'Autre quartier',
  ],
  Kribi: [
    'Afan-Mabé',
    'Bebambwe',
    'Bibolo',
    'Bikondo',
    'Bongahele',
    'Bongandoué',
    'Bwambé',
    'Centre-ville',
    'Dombé',
    'Ebome',
    'Eboundja',
    'Ebouyoe',
    'Elabé',
    'Lendé Aviation',
    'Lendé-Dibé',
    'Lobé',
    'Lolabé',
    'Londji',
    'Louma',
    'Massaka',
    'Mboamanga',
    'Mbeka\'a',
    'Mokolo',
    'Mpolongwe',
    'Mpalla',
    'New-Town',
    'Ngoye',
    'Nziou',
    'Petit Paris',
    'Port',
    'Talla',
    'Zaïre',
    'Autre quartier',
  ],
  Garoua: [
    'Batouaré',
    'Bibémiré',
    'Bocklé',
    'Boggaré',
    'Centre-ville',
    'Djamboutou',
    'Djalingo',
    'Do Wouro',
    'Faliré',
    'Foulbéré',
    'Haoussaré',
    'Lopéré',
    'Marouaré',
    'Plateau',
    'Poumpoumré',
    'Quartier Bamiléké',
    'Roumdé-Adjia',
    'Sanguéré',
    'Yelwa',
    'Autre quartier',
  ],
  Bamenda: [
    'Abangoh',
    'Achichum',
    'Alahnting',
    'Ayaba',
    'Bamenda-Nkwe',
    'Centre-ville',
    'Commercial Avenue',
    'Foncha Street',
    'Hospital Roundabout',
    'Kenelari',
    'Mankon',
    'Menda-Nkwe',
    'Meta Quarter',
    'Mile 2',
    'Mile 4',
    'Mulang',
    'Nkwen',
    'Ntanche',
    'Ntarikon',
    'Old Town',
    'Up Station',
    'Autre quartier',
  ],
  Maroua: [
    'Bamaré',
    'Baouliwol',
    'Centre-ville',
    'Dakar',
    'Diguirwo',
    'Dingui',
    'Djarengol',
    'Djoudandou',
    'Djoulgouf',
    'Domayo',
    'Doualare',
    'Douggoi',
    'Founangue',
    'Gaklé',
    'Gayak',
    'Hardéo',
    'Hodango',
    'Idao',
    'Kakatare',
    'Kodek',
    'Kodjoleo',
    'Kongola',
    'Kountcharé',
    'Lopéré',
    'Louggeo',
    'Makabaye',
    'Mambang',
    'Massinaka',
    'Mayel-Ibbé',
    'Mbarmaré',
    'Mérem',
    'Missinguiléo',
    'Ouro Bikordi',
    'Ouro Dolé',
    'Ouro Ladé',
    'Ouro Saïd',
    'Ouro Tchédé',
    'Pallar',
    'Pont Vert',
    'Sarare',
    'Tchadéo',
    'Zokok',
    'Autre quartier',
  ],
  Ngaoundéré: [
    'Baladji',
    'Bali',
    'Bamyanga',
    'Béka',
    'Boumdjere',
    'Burkina',
    'Centre-ville',
    'Dang',
    'Dara Salam',
    'Gadamabanga',
    'Hamadjangui',
    'Haoussa',
    'Joli Soir',
    'Kantalan',
    'Longtré',
    'Madagascar',
    'Margueleng',
    'Marma',
    'Mbalam',
    'Mbideng',
    'Ngaoussay',
    'Ngaounday',
    'Nord Cifan',
    'Onaref',
    'Sabongari',
    'Tongo',
    'Wakwa',
    'Yarbang',
    'Yoko',
    'Autre quartier',
  ],
  Ebolowa: [
    'Amang',
    'Angalé',
    'Angounou',
    'Bilon',
    'Centre-ville',
    'Ekombité',
    'Elat',
    'Enongal',
    'Essinguili',
    'Mekalat',
    'Nko\'ovos',
    'Oyenga',
    'Autre quartier',
  ],
  Buea: [
    'Bonakanda',
    'Bonjongo',
    'Buea Station',
    'Buea Town',
    'Centre-ville',
    'Great Soppo',
    'Mile 17',
    'Molyko',
    'Muea',
    'Tole',
    'Autre quartier',
  ],
  Kumba: [
    'Barombi Kang',
    'Barombi Mbo',
    'Bokoko',
    'Cattle Market',
    'Centre-ville',
    'Dschang Quarter',
    'Fiango',
    'Kossalal',
    'Kumba Mbeng',
    'Kumba Njembe',
    'Kumba Njuki',
    'Makatol',
    'Makiti',
    'Malende',
    'Mambanda',
    'Mile On',
    'Monte Carlo',
    'Mundame',
    'Mukonje',
    'Nkake',
    'Nkamundikum',
    'Ntam',
    'Quartier Administratif',
    'Tancha',
    'Teke',
    'Utoko',
    'Autre quartier',
  ],
  Limbe: [
    'Batoke',
    'Bobende',
    'Boando',
    'Bota',
    'CDC Quarter',
    'Centre-ville',
    'Custom Quarter',
    'Federal Quarter',
    'GRA',
    'Hospital Layout',
    'Limbola',
    'Mabeta',
    'Mile 2',
    'Mile 4',
    'Mokundange',
    'Mokindi',
    'Motowoh',
    'New Town',
    'Ngeme',
    'Unity Quarter',
    'Wovia',
    'Autre quartier',
  ],
  Bertoua: [
    'Bamvele',
    'Birpondo',
    'Bodomo',
    'Centre-ville',
    'Dara Salam',
    'Gaimona',
    'Haoussa',
    'Kano',
    'Koume-Bonis',
    'Madagascar',
    'Mokolo',
    'Monou',
    'Ndouan',
    'Ndongoffi',
    'Ngaïkada',
    'Nkolbikon',
    'Nyangaza',
    'Radio',
    'Tigaza',
    'Woulamayo',
    'Yademe',
    'Autre quartier',
  ],
  Edéa: [
    'Amour',
    'Béon',
    'Bisseke',
    'Centre commercial',
    'Centre-ville',
    'Domaine Sanaga',
    'Ékité',
    'Gare',
    'Haoussa',
    'Mbanda',
    'Nkongmondo',
    'Plateau administratif',
    'Pongo',
    'Zanga',
    'Autre quartier',
  ],
  Nkongsamba: [
    'Bonangoh',
    'Centre-ville',
    'Eboum',
    'Edip',
    'Edjogmoa',
    'Ehalmoa',
    'Ekel-Ko\'o',
    'Ekel-Mbeng',
    'Ekangté-Mbeng',
    'Mbaressoumtou',
    'Mouambo\'o',
    'Mouandja',
    'Ndogmoa',
    'Nlonko\'o',
    'Sosso',
    'Autre quartier',
  ],
  Foumban: [
    'Centre-ville',
    'Fountain',
    'Kounga',
    'Koukwat',
    'Machiwom',
    'Makouen',
    'Malatam',
    'Mambain',
    'Manka',
    'Montagne Sacrée',
    'Njiden',
    'Njimbam',
    'Njindare',
    'Njintout',
    'Njiloum',
    'Njimatié',
    'Njinka',
    'Njissé',
    'Njiyouom',
    'Quartier Administratif',
    'Quartier Gabon',
    'Autre quartier',
  ],
  Dschang: [
    'Centre-ville',
    'Fongo-Ndeng',
    'Foréké-Dschang',
    'Fossong-Wentcheng',
    'Foto',
    'Fotetsa',
    'Haoussa',
    'Marché Central',
    'Autre quartier',
  ],
  Mbalmayo: [
    'Afanloum',
    'Centre-ville',
    'Melombo',
    'Nkol-Mabang',
    'Nyong',
    'Autre quartier',
  ],
  Kousséri: [
    'Abouzréga',
    'Adjaïné',
    'Centre-ville',
    'Djambalbar',
    'Djoumbalbou',
    'Goré',
    'Guebala',
    'Haoussa',
    'Kamboula',
    'Kawadji',
    'Lacta',
    'Madagascar',
    'Maïnani',
    'Massaki',
    'Ndjagaré',
    'Ngamadja',
    'Rigguil Kotoko',
    'Rigguil Mousgoum',
    'Séhéba',
    'Autre quartier',
  ],
};

const FALLBACK_NEIGHBORHOODS = ['Centre-ville', 'Autre quartier'];

export function getNeighborhoodsForZoneName(zoneName: string): string[] {
  const key = shortCityLabel(zoneName);
  return DELIVERY_NEIGHBORHOODS[key] ?? FALLBACK_NEIGHBORHOODS;
}
